const translations = {
  fr: {
    title: "Peter Castro",
    description: "Portfolio de Peter Castro, anthropologue, artiste et chercheur : recherche, bande dessinée et création plastique par couches.",
    skip: "Aller au contenu",
    navLabel: "Navigation principale",
    homeLabel: "Peter Castro — accueil",
    languageLabel: "Langue",
    lightboxLabel: "Aperçu de l’œuvre",
    close: "Fermer",
    navResearch: "Enquêter",
    navCreations: "Créer",
    navWorkshop: "Faire atelier",
    navAbout: "Parcours",
    role: "Anthropologue · artiste · chercheur",
    heroLine1: "Dessiner",
    heroLine2: "des mondes,",
    heroLine3: "suivre leurs traces,",
    heroLine4: "couche après couche.",
    heroIntro: "Je suis anthropologue, artiste et chercheur. Mon travail se déploie entre l’enquête en sciences sociales, une pratique artistique personnelle et la création collective d’ateliers.",
    factsLabel: "Repères",
    based: "Paris",
    territories: "Colombie · Mexique · France",
    yearFocus: "Recherche-création · 2026",
    pathsLabel: "Trois entrées dans le portfolio",
    partOneLabel: "PARTIE I",
    partTwoLabel: "PARTIE II",
    partThreeLabel: "PARTIE III",
    sitePlanKicker: "Introduction · mode d’emploi",
    sitePlanTitle: "Un site, trois pratiques.",
    sitePlanText: "Ce portfolio distingue trois manières de travailler. Enquêter réunit les sciences sociales et la méthode dessinée. Créer présente une pratique artistique personnelle et autonome. Faire atelier rassemble les expériences produites avec d’autres personnes. Les trois espaces se répondent sans se confondre.",
    sitePlanLabel: "Plan du portfolio",
    pathResearch: "Enquêter",
    pathResearchText: "Comprendre des situations par l’anthropologie, le terrain et le dessin.",
    pathCreations: "Créer",
    pathCreationsText: "Explorer des formes, des matières et des mondes personnels.",
    pathWorkshop: "Faire atelier",
    pathWorkshopText: "Produire des images et des savoirs dans la relation avec d’autres.",
    palimpsestKicker: "Fil conducteur",
    traceLabel: "TRACE 01—∞",
    palimpsestStatement: "Voir les couches, puis revenir vers l’origine de la trace.",
    palimpsestBody: "L’enquête, la création personnelle et les ateliers restent des pratiques distinctes. Elles se rencontrent dans une même attention aux couches, aux transformations et à l’origine des traces, sans devenir pour autant une seule pratique.",
    palimpsestWords: "corps · mémoire · reprise · retour",
    heroCaption: "Dessiner des mondes · d’après un dessin de Critón",
    heroYear: "2026",
    openHero: "Agrandir l’œuvre Dessiner des mondes",
    altHero: "Enfant dessinant un monde peuplé de figures et de formes, réinterprété par Peter Castro à partir d’un dessin de Critón",
    materialKicker: "Gestes, surfaces, reprises",
    materialTitle: "Intervenir la matière",
    materialText: "Ces œuvres naissent d’interventions successives : anverso et reverso, couches de marbrure, aquarelle, fil, collage, déchirure et recomposition. Chaque surface conserve les temps et les matériaux qui l’ont transformée.",
    materialGalleryLabel: "Trois œuvres par interventions matérielles",
    hominidsCaption: "Anverso / reverso · intervention et marbrure",
    watercolourMarblingCaption: "Aquarelle et marbrure",
    marineFigureCaption: "Figure marine · broderie, collage, aquarelle, déchirure et recomposition",
    openHominids: "Agrandir le diptyque de primates",
    openWatercolourMarbling: "Agrandir l’aquarelle et marbrure",
    openMarineFigure: "Agrandir la figure marine en techniques mixtes",
    altHominids: "Diptyque symétrique de primates imprimés et de couches roses, rouges et grises de marbrure",
    altWatercolourMarbling: "Aquarelle abstraite à dominante jaune, bleue et rouge, traversée de lignes noires et de marbrure",
    altMarineFigure: "Figure marine sur textile rouge et turquoise, composée de broderie, collage, aquarelle et fragments recomposés",
    researchPart: "Partie I",
    worksTitle: "Enquêter",
    worksIntro: "Dans une recherche achevée, on voit surtout un résultat cohérent. Je m’intéresse aux brouillons : aux moments où la compréhension vacille et doit être reprise.",
    genesisKicker: "Genèse d’une pratique",
    genesisTitle: "Comment le dessin est entré dans l’enquête",
    researchTocLabel: "Sommaire de la recherche",
    researchTocKicker: "Dans cette partie",
    researchTocGenesis: "La genèse",
    researchTocGenesisText: "Comment le dessin est entré dans l’enquête.",
    researchTocMethod: "Les opérations",
    researchTocMethodText: "Ce que la bande dessinée rend possible.",
    researchTocCases: "Les rencontres",
    researchTocCasesText: "Comment les cas ont transformé la méthode.",
    researchTocProjects: "Les projets",
    researchTocProjectsText: "Trois étapes d’une recherche en cours.",
    genesisIntro: "Je n’ai pas commencé par inventer une méthode. Le dessin est devenu un outil d’enquête à travers une suite d’expériences.",
    genesis1Title: "Avant la méthode",
    genesis1Text: "Le dessin était déjà une pratique personnelle et expérimentale, avant les sciences sociales.",
    genesis2Title: "Dessiner le terrain",
    genesis2Text: "En Amazonie colombienne, croquis et aquarelles m’ont appris à ralentir et à regarder autrement.",
    genesis3Title: "Un terrain interrompu",
    genesis3Text: "La pandémie a interrompu le terrain. Les images m’ont permis de revenir vers une expérience encore sans forme.",
    genesis4Title: "Revenir par la bande dessinée",
    genesis4Text: "À l’IHEAL, les ateliers de Romain Dutter ont conduit à dix-neuf pages sur mon arrivée en Amazonie.",
    genesis5Title: "Diana renvoie le regard",
    genesis5Text: "En reprenant la scène avec Diana Gil Bora, la question s’est inversée : que voient les autres du chercheur ?",
    researchProjectsKicker: "Projets de recherche",
    researchProjectsTitle: "Projets et récits dessinés",
    researchProjectsText: "Chaque projet apparaît d’abord sous forme de résumé. Ouvrez-le pour parcourir ses images, ses versions et ses choix méthodologiques.",
    expandOpen: "Ouvrir cette section",
    expandClose: "Refermer cette section",
    journeyLabel: "PARCOURS",
    troubleMeta: "Projet doctoral · EHESS · 2026",
    troubleTitle: "Trouble dans l’enquête",
    troubleSubtitle: "Suivre ce que devient une scène lorsqu’elle est racontée, dessinée, retournée et reprise.",
    troubleText: "Ce projet doctoral prolonge les apprentissages du mémoire. Les scènes de trouble y servent de portes d’entrée empiriques : la bande dessinée permet de suivre leurs interprétations successives, de les faire circuler et d’observer ce que les retours transforment.",
    troubleNoteLabel: "Question actuelle",
    troubleQuestion: "Que devient une interprétation lorsqu’elle peut être dessinée, discutée, corrigée, refusée ou laissée ouverte ?",
    troubleImage1Caption: "Le terrain raconté par le chercheur",
    troubleImage2Caption: "Le terrain renvoyé vers l’enquêteur",
    openTrouble1: "Agrandir la première planche de Trouble dans l’enquête",
    openTrouble2: "Agrandir la deuxième planche de Trouble dans l’enquête",
    altTrouble1: "Première planche de bande dessinée du projet doctoral Trouble dans l’enquête",
    altTrouble2: "Deuxième planche montrant des interprétations concurrentes d’une situation de terrain",
    imposteurMeta: "L’Imposteur · revue doctorale · 2025",
    imposteurTitle: "Entrer en thèse dans une autre langue",
    imposteurText: "Deux planches autobiographiques reviennent sur mon arrivée en France et sur le double travail imposé par la langue académique : penser en espagnol, reformuler en français, puis affronter l’orthographe comme critère de légitimité. La bande dessinée y apparaît à la fois comme langage scientifique et comme manière d’ouvrir une méthode propre.",
    imposteurNoteLabel: "Peur d’entrée en thèse",
    imposteurNote: "Isolement, précarité matérielle et perte des liens sociaux.",
    imposteurCaption1: "Arrivée en France et langue académique",
    imposteurCaption2: "La bande dessinée comme ouverture méthodologique",
    imposteurCaption3: "La plus grande peur à l’entrée en thèse",
    openImposteur1: "Agrandir la première planche publiée dans L’Imposteur",
    openImposteur2: "Agrandir la deuxième planche publiée dans L’Imposteur",
    openImposteur3: "Agrandir l’illustration sur la peur d’entrée en thèse",
    altImposteur1: "Planche autobiographique sur l’arrivée à Toulouse et les difficultés avec la langue académique française",
    altImposteur2: "Planche autobiographique sur la découverte de la bande dessinée comme langage scientifique",
    altImposteur3: "Personnage isolé dans un cercle de lumière, entouré de silhouettes et de piles de livres",
    observerMeta: "Mémoire de Master 2 · IHEAL · 2024",
    observerTitle: "Observer et être observé",
    observerText: "Une socio-anthropologie des anthropologues par la bande dessinée. L’enquête examine comment les expériences de terrain, les positions sociales et les relations avec les interlocuteurs transforment la pratique scientifique — et comment le chercheur est, lui aussi, observé et interprété.",
    masterResult: "Mémoire : 17/20",
    masterMention: "Mention Très Bien",
    observerCaption1: "La relation d’enquête comme construction réciproque",
    observerCaption2: "La bande dessinée comme méthode d’enquête",
    observerCaption3: "De l’entretien à la planche : le cas de Stéphanie",
    openObserver1: "Agrandir Observer et être observé",
    openObserver2: "Agrandir les dessins de la méthode d’enquête",
    openObserver3: "Agrandir le processus de Stéphanie",
    altObserver1: "Deux personnes assises autour d’une table, chacune projetant une représentation différente du terrain",
    altObserver2: "Assemblage de dessins montrant les étapes de production d’une bande dessinée à partir d’entretiens",
    altObserver3: "Portrait, éléments d’entretien et storyboard autour de l’expérience de Stéphanie",
    palimpsesteMeta: "Bande dessinée de terrain · 2022–en cours",
    palimpsesteTitle: "Trajet du corps palimpseste",
    palimpsesteSubtitle: "Une trajectoire entre Kennedy, la France et l’Amazonie, réécrite depuis la relation d’enquête.",
    palimpsesteText: "À partir de mon travail de terrain et des échanges avec Diana Gil Bora, la bande dessinée reconstruit les conditions qui m’ont conduit jusqu’à l’Amazonie colombienne. Elle ne raconte pas seulement un déplacement géographique : elle suit les souvenirs, les assignations et les malentendus qui se déposent dans le corps du chercheur et transforment sa manière de voir.",
    palimpsesteAxisLabel: "Trajet visible",
    palimpsesteAxis: "Kennedy → France → Amazonie → retour sur l’enquête",
    v3GalleryLabel: "Cinq pages de la version 3",
    v3Kicker: "Version 3 · réécriture actuelle",
    v3Title: "La scène avant son explication",
    v3Intro: "Le feu, la maloca, le mambe et les silences introduisent d’abord la situation. Le parcours autobiographique arrive ensuite : l’interprétation naît dans les images avant d’être formulée.",
    v3Caption1: "Entrer dans la scène",
    v3Caption2: "Une certitude commence à vaciller",
    v3Caption3: "Le malentendu prend corps",
    v3Caption4: "Le corps dans l’échelle du territoire",
    v3Caption5: "Revenir à Kennedy, origine de la trace",
    openV3P1: "Agrandir la première page de la version 3",
    openV3P2: "Agrandir la deuxième page de la version 3",
    openV3P3: "Agrandir la troisième page de la version 3",
    openV3P4: "Agrandir la quatrième page de la version 3",
    openV3P5: "Agrandir la cinquième page de la version 3",
    altV3P1: "Séquence nocturne montrant le feu, la maloca, le chercheur et une cuillerée de mambe",
    altV3P2: "Conversation dans la maloca sur l’Église, les pauvres et le péché écologique",
    altV3P3: "Dialogue où le chercheur s’étonne qu’un prêtre prenne du mambe",
    altV3P4: "Le chercheur assis sous un arbre immense au bord de l’eau en Amazonie",
    altV3P5: "Cartes de la Colombie, Bogotá et Kennedy menant à un souvenir d’enfance à Casablanca",
    layersKicker: "Palimpseste de fabrication",
    layersTitle: "Ce que la réécriture déplace",
    layersIntro: "La première version de 2022 n’est pas exposée comme une seconde œuvre complète. Quatre confrontations précises montrent plutôt comment le point de vue, le corps et l’échelle du récit ont changé. Ouvrez chaque strate pour voir les deux états.",
    layer1Title: "Du surplomb à la présence",
    layer1Text: "En 2022, la scène était observée depuis le haut. Dans la version 3, mon visage et mon arrivée s’intercalent entre la maloca et le mambe : l’enquêteur n’est plus hors champ.",
    layer2Title: "Du dialogue au trouble relationnel",
    layer2Text: "Les paroles restent proches, mais les regards, les distances et la durée accordée aux gestes rendent désormais visible la surprise du chercheur et la réponse de son interlocuteur.",
    layer3Title: "Du symbole au corps situé",
    layer3Text: "La flamme abstraite de la première version devient un corps minuscule sous un arbre immense. La trajectoire n’est plus seulement racontée : elle acquiert une échelle, un poids et un lieu.",
    layer4Title: "Du souvenir à l’échelle du territoire",
    layer4Text: "Le souvenir domestique s’ouvre désormais par emboîtements : Colombie, Bogotá, Kennedy, Casablanca, puis l’appartement. Revenir à l’origine signifie traverser plusieurs couches d’espace et de mémoire.",
    layerV1Caption: "V1 · première formulation · 2022",
    layerV3Caption: "V3 · réécriture actuelle · 2026",
    openV1P1: "Agrandir la première page de 2022",
    openV1P3: "Agrandir la troisième page de 2022",
    openV1P4: "Agrandir la quatrième page de 2022",
    openV1P5: "Agrandir la cinquième page de 2022",
    altV1P1: "Première version de 2022 observant la maloca depuis le haut",
    altV1P3: "Première version du dialogue sur le mambe, la prêtrise et l’Église",
    altV1P4: "Première version associant la trajectoire France-Amazonie à une grande flamme",
    altV1P5: "Première version ouvrant le souvenir d’enfance à Casablanca par une vue de Bogotá",
    mamaMeta: "Récit dessiné familial · 2022",
    mamaTitle: "Où est ta maman ?",
    mamaText: "Un récit personnel du côté maternel, traversé par la mémoire, l’absence et les silences transmis entre générations. L’image y fait revenir ce qui n’a pas été raconté et compose avec les vides laissés dans l’histoire familiale.",
    storiesMeta: "Bandes dessinées · 2023–2024",
    storiesTitle: "Retour, mémoire, filiation",
    storiesText: "Deux récits reviennent vers l’Amazonie colombienne. Retour vers l’Amazonie reprend un ancien terrain à partir d’un nouvel échange avec Diana Gil Bora. Où est ta maman explore la mémoire familiale, l’absence maternelle et les silences hérités.",
    amazonCaption: "Retour vers l’Amazonie · 2024",
    mamaCaption: "Où est ta maman · 2023",
    storyLabel: "RÉCIT",
    reportageLabel: "REPORTAGE",
    openAmazon1: "Agrandir Retour vers l’Amazonie",
    openAmazon2: "Agrandir une page de Retour vers l’Amazonie",
    openMama1: "Agrandir Où est ta maman",
    openMama2: "Agrandir la deuxième page de Où est ta maman",
    altAmazon1: "Séquence nocturne en noir et blanc montrant l’arrivée dans une maloca amazonienne",
    altAmazon2: "Page de bande dessinée en noir et blanc autour de la coca, du tabac et de la parole",
    altMama1: "Page en noir et blanc sur l’absence de la mère, les souvenirs et la filiation",
    altMama2: "Page dessinée montrant la trajectoire familiale et rurale de la mère",
    galereMeta: "Collectif de recherche-création · 2025–2026",
    galereText: "Collectif cofondé autour de la bande dessinée et des sciences sociales. Ateliers, fanzines et affiches transforment les difficultés partagées de la recherche en matière de création, de médiation et de discussion collective.",
    galereCaption1: "Une recherche collective sur la recherche",
    galereCaption2: "Affiche pour les ateliers du collectif",
    galereCaption3: "La bande dessinée comme objet éditorial",
    openGalere1: "Agrandir une bande dessinée de La Galère",
    openGalere2: "Agrandir l’affiche de La Galère",
    openGalere3: "Agrandir les éditions de La Galère",
    altGalere1: "Bande dessinée bleu et noir sur les difficultés partagées du travail de recherche",
    altGalere2: "Aquarelle circulaire multicolore représentant les membres du collectif autour d’un centre rouge et bleu",
    altGalere3: "Fanzines, affiches et pages imprimées produits par le collectif La Galère",
    plasticMeta: "Carnet · broderie · aquarelle · collage · 2019–2025",
    plasticTitle: "Corps, masques, transformations",
    plasticText: "Une recherche plastique autonome traversée par des visages, des formes organiques, des ouvertures et des figures doubles. L’aquarelle se mêle au fil, à l’encre et au collage ; chaque reprise conserve la trace des états antérieurs de l’image.",
    plasticCaption: "Recherches plastiques · techniques mixtes",
    openPlastic: "Agrandir les recherches plastiques",
    altPlastic: "Double page de recherches plastiques aux fils brodés roses et bleus, collages et couches d’aquarelle très colorées",
    createPart: "Partie II",
    creationsTitle: "Créer",
    creationsIntro: "Aquarelles, dessins, broderies, collages et carnets composent une pratique artistique personnelle qui précède mon travail en sciences sociales. Elle possède sa propre histoire et n’a pas besoin de devenir une méthode pour exister, même si certains gestes circulent entre les deux espaces.",
    workshopPart: "Partie III",
    workshopTitle: "Faire atelier",
    workshopIntro: "Un atelier n’est pas seulement un lieu où transmettre une technique. C’est une situation où des personnes dessinent, interprètent et transforment ensemble ce qui peut être su, raconté ou partagé.",
    workshopProcessKicker: "Une pratique de relation",
    workshopProcessTitle: "L’atelier fabrique un espace commun.",
    workshopProcessIntro: "Je ne viens pas avec une image déjà décidée. Le cadre se construit à partir de ce que les personnes apportent, des formes qu’elles essaient et des désaccords qui apparaissent.",
    workshopStep1Title: "Mettre en situation",
    workshopStep1Text: "Partir d’un récit, d’une difficulté ou d’une expérience partageable.",
    workshopStep2Title: "Fabriquer ensemble",
    workshopStep2Text: "Dessiner, découper, monter et comparer sans imposer une seule manière de faire.",
    workshopStep3Title: "Faire circuler",
    workshopStep3Text: "Transformer les essais en fanzine, affiche, exposition ou objet de discussion.",
    constellationKicker: "Aquarelles · collage · papier",
    constellationTitle: "Vía Láctea / Bóvedas celestes",
    constellationText: "Trois paysages intérieurs où la lumière se dépose par couches. Vía Láctea assemble pigments, fragments collés et grattage sur format A4 ; les deux Bóvedas celestes prolongent ce mouvement dans des formats plus petits, entre ciel, profondeur et foyer.",
    constellationGalleryLabel: "Les deux Bóvedas celestes",
    viaLacteaCaption: "Vía Láctea · aquarelle, collage et grattage sur papier · A4",
    bovedasICaption: "Bóvedas celestes I · aquarelle sur papier · petit format",
    bovedasIICaption: "Bóvedas celestes II · aquarelle sur papier · petit format",
    openViaLactea: "Agrandir Vía Láctea",
    openBovedasI: "Agrandir Bóvedas celestes I",
    openBovedasII: "Agrandir Bóvedas celestes II",
    altViaLactea: "Aquarelle turquoise constellée de points colorés, de fragments collés et de traces de grattage",
    altBovedasI: "Aquarelle de voûte céleste aux arcs jaune, orange, vert, rose et bleu",
    altBovedasII: "Aquarelle de voûte céleste rouge, noire, bleue et turquoise autour d’un centre lumineux",
    studioKicker: "Atelier · œuvres en cours · Paris",
    studioTitle: "L’atelier comme palimpseste vivant",
    studioText: "Les œuvres ne restent pas isolées dans un dossier. Elles se répondent sur les murs, les cordes et la table : aquarelles, papiers découpés, fils, encres et essais encore ouverts. Chaque déplacement produit une nouvelle relation entre les formes.",
    studioCaption: "Accrocher, déplacer, recouvrir, reprendre : l’espace de travail garde la mémoire des gestes.",
    studioGalleryLabel: "Œuvres et espace de travail",
    studioMark1: "Vue d’ensemble · atelier",
    studioMark2: "Suspendre · faire dialoguer",
    studioMark3: "Mur · états provisoires",
    studioMark4: "Matière · eau · fil",
    studioMark5: "Table · couleurs en mouvement",
    openStudio1: "Agrandir la vue de l’atelier",
    openStudio2: "Agrandir les œuvres suspendues",
    openStudio3: "Agrandir le mur de recherches plastiques",
    openStudio4: "Agrandir les recherches de matière",
    openStudio5: "Agrandir la table de travail",
    altStudio1: "Vue générale de l’atelier de Peter Castro avec œuvres, livres et outils",
    altStudio2: "Œuvres organiques suspendues devant une bibliothèque",
    altStudio3: "Mur couvert d’aquarelles, de papiers découpés et de formes organiques",
    altStudio4: "Aquarelle bleue, matière textile et papier suspendus dans l’atelier",
    altStudio5: "Table de travail avec aquarelles, pinceaux et petites peintures",
    salesKicker: "Œuvres originales · éditions · commandes",
    salesTitle: "Œuvres originales et commandes.",
    salesText: "Écrivez-moi avec le titre d’une œuvre : je vous répondrai avec ses dimensions, sa technique, sa disponibilité, son prix et les modalités d’envoi. Je peux aussi étudier une commande.",
    salesCta: "Demander disponibilité et prix ↗",
    reportMeta: "Commande de reportage dessiné · ENS · 2026",
    reportTitle: "Observation et évocation",
    reportText: "Dessins réalisés sur le vif autour d’une pièce de théâtre à l’École normale supérieure. Le trait enregistre les moments observés et évoque les présences absentes — entre écoute, mémoire et traduction visuelle.",
    reportCaption: "Reportage dessiné : observation et évocation",
    openReport1: "Agrandir le croquis de l’entrée",
    openReport2: "Agrandir le croquis du public",
    openReport3: "Agrandir le croquis de la scène",
    openReport4: "Agrandir le dessin face à la mer",
    altReport1: "Croquis à l’encre d’un rassemblement à l’entrée d’un théâtre",
    altReport2: "Croquis du public observant une représentation théâtrale",
    altReport3: "Croquis d’une scène éclairée avec des interprètes alignés",
    altReport4: "Personnage minuscule debout face à une vaste mer dessinée à l’encre",
    methodTitle: "Ce que la bande dessinée fait à l’enquête",
    methodIntro: "De cette trajectoire se dégagent quatre opérations. Elles ne forment pas une recette : elles décrivent ce que le dessin a progressivement rendu possible dans mes enquêtes.",
    conceptLabel: "Principe de travail",
    conceptTitle: "Dessiner ne vient pas après l’enquête.",
    conceptText: "Le dessin déplace l’attention, oblige à rendre visibles des choix d’interprétation et ouvre la possibilité d’un retour. Une image peut être discutée, corrigée, refusée ou laissée ouverte.",
    methodProtocolTitle: "Quatre opérations apprises en pratiquant",
    m1Title: "Regarder autrement",
    m1Text: "Dessiner pendant ou après une rencontre ralentit l’observation et déplace l’attention vers des gestes, des distances et des détails que la seule prise de notes peut laisser de côté.",
    m2Title: "Composer, donc interpréter",
    m2Text: "Choisir une scène, un cadrage, une séquence ou un silence oblige à concrétiser ce que l’on croit avoir compris. Le montage expose ainsi les décisions du chercheur.",
    m3Title: "Renvoyer l’image",
    m3Text: "Faire circuler la planche auprès des personnes rencontrées transforme l’interprétation en objet discutable. Elles peuvent la préciser, la déplacer, la refuser ou proposer une autre scène.",
    m4Title: "Conserver les versions",
    m4Text: "Une correction ne remplace pas silencieusement l’état précédent. Les versions gardent la trajectoire de l’analyse et montrent comment une compréhension s’est transformée.",
    casesKicker: "La méthode par les cas",
    casesTitle: "Ce sont les rencontres qui ont fait évoluer la méthode.",
    casesIntro: "Chaque expérience a posé un problème différent. Ensemble, elles montrent une méthode en train de se construire plutôt qu’un protocole appliqué d’avance.",
    caseCeline: "Une scène d’arrivée solitaire semblait graphiquement cohérente, mais elle était fausse. Sa correction a rendu visible mon interprétation et relancé l’enquête.",
    caseStephanie: "Le passage de l’entretien au dessin a permis de comprendre plus finement les positions, les émotions et les relations contenues dans son récit.",
    caseLouise: "L’image a fait apparaître que la migration structurait davantage son expérience que le terrain formel que je pensais devoir représenter.",
    caseJeanne: "Un livre brodé et un livre muet ont posé la question de la restitution : que peut-on transmettre sans refermer le sens à la place de l’autre ?",
    caseAdrien: "L’écart entre l’image produite et sa réponse n’a pas été un échec à effacer. Il a conduit à une nouvelle enquête et à une interprétation révisée.",
    lineagesTitle: "Une généalogie graphique resserrée",
    lineagesIntro: "Quatre rencontres intellectuelles et pratiques ont directement déplacé ma manière de faire de la bande dessinée en recherche.",
    lineage1Text: "Ses ateliers à l’IHEAL m’ont appris à transformer une expérience de terrain en scènes, séquences et pages, sans réduire la bande dessinée à une illustration.",
    lineage2Text: "Leurs expériences montrent que l’image peut participer à la production collective du savoir et à sa circulation, au lieu d’arriver seulement à la fin de la recherche.",
    lineage3Text: "Son travail aide à penser ce que le changement de médium transforme dans la posture du chercheur, l’écriture et les relations de l’enquête.",
    lineage4Text: "Elle propose de considérer la bande dessinée comme une pratique de recherche à part entière : une manière de penser par l’espace, la séquence et le montage.",
    aboutTitle: "À propos",
    aboutLead: "Je suis anthropologue, artiste et chercheur colombien, basé à Paris.",
    aboutText: "Formé en Colombie, au Mexique et en France, je travaille au croisement de l’enquête qualitative, de la narration graphique et de la production de savoirs sensibles. Mon parcours traverse l’anthropologie, les sciences sociales et la recherche-création.",
    aboutCollective: "Je cofonde en 2025 La Galère, un collectif interuniversitaire qui développe des ateliers, fanzines, expositions et restitutions dessinées en sciences sociales.",
    cvDownload: "Télécharger le CV · PDF ↗",
    edu1: "Année préparatoire au doctorat · EHESS",
    edu2: "DIU ArTeC · Recherche-création · Université Paris 8",
    edu3: "Master 2 Sciences sociales, Anthropologie · IHEAL, Sorbonne Nouvelle",
    contactKicker: "Recherche · ateliers · édition · exposition",
    contactTitle: "Parlons d’un projet.",
    footerRole: "Dessin, enquête & recherche-création",
    backTop: "Retour à l’index ↑"
  },
  es: {
    title: "Peter Castro",
    description: "Portafolio de Peter Castro, antropólogo, artista e investigador: investigación, historieta y creación plástica por capas.",
    skip: "Ir al contenido",
    navLabel: "Navegación principal",
    homeLabel: "Peter Castro — inicio",
    languageLabel: "Idioma",
    lightboxLabel: "Vista ampliada de la obra",
    close: "Cerrar",
    navResearch: "Investigar",
    navCreations: "Crear",
    navWorkshop: "Hacer taller",
    navAbout: "Trayectoria",
    role: "Antropólogo · artista · investigador",
    heroLine1: "Dibujar",
    heroLine2: "mundos,",
    heroLine3: "seguir sus huellas,",
    heroLine4: "capa sobre capa.",
    heroIntro: "Soy antropólogo, artista e investigador. Mi trabajo se despliega entre la investigación en ciencias sociales, una práctica artística personal y la creación colectiva de talleres.",
    factsLabel: "Referencias",
    based: "París",
    territories: "Colombia · México · Francia",
    yearFocus: "Investigación-creación · 2026",
    pathsLabel: "Tres entradas al portafolio",
    partOneLabel: "PARTE I",
    partTwoLabel: "PARTE II",
    partThreeLabel: "PARTE III",
    sitePlanKicker: "Introducción · modo de uso",
    sitePlanTitle: "Un sitio, tres prácticas.",
    sitePlanText: "Este portafolio distingue tres maneras de trabajar. Investigar reúne las ciencias sociales y el método dibujado. Crear presenta una práctica artística personal y autónoma. Hacer taller reúne las experiencias producidas con otras personas. Los tres espacios dialogan sin confundirse.",
    sitePlanLabel: "Índice del portafolio",
    pathResearch: "Investigar",
    pathResearchText: "Comprender situaciones mediante la antropología, el trabajo de campo y el dibujo.",
    pathCreations: "Crear",
    pathCreationsText: "Explorar formas, materias y mundos personales.",
    pathWorkshop: "Hacer taller",
    pathWorkshopText: "Producir imágenes y saberes en relación con otras personas.",
    palimpsestKicker: "Hilo conductor",
    traceLabel: "HUELLA 01—∞",
    palimpsestStatement: "Ver las capas y después volver al origen de la huella.",
    palimpsestBody: "La investigación, la creación personal y los talleres siguen siendo prácticas diferentes. Se encuentran en una misma atención a las capas, las transformaciones y el origen de las huellas, sin convertirse por eso en una sola práctica.",
    palimpsestWords: "cuerpo · memoria · reelaboración · retorno",
    heroCaption: "Dibujar mundos · a partir de un dibujo de Critón",
    heroYear: "2026",
    openHero: "Ampliar la obra Dibujar mundos",
    altHero: "Niño dibujando un mundo de figuras y formas, reinterpretado por Peter Castro a partir de un dibujo de Critón",
    materialKicker: "Gestos, superficies, reescrituras",
    materialTitle: "Intervenir la materia",
    materialText: "Estas obras nacen de intervenciones sucesivas: anverso y reverso, capas de marmoleo, acuarela, hilo, collage, rasgado y recomposición. Cada superficie conserva los tiempos y materiales que la transformaron.",
    materialGalleryLabel: "Tres obras por intervenciones materiales",
    hominidsCaption: "Anverso / reverso · intervención y marmoleo",
    watercolourMarblingCaption: "Acuarela y marmoleo",
    marineFigureCaption: "Figura marina · bordado, collage, acuarela, rasgado y recomposición",
    openHominids: "Ampliar el díptico de homínidos",
    openWatercolourMarbling: "Ampliar la acuarela y marmoleo",
    openMarineFigure: "Ampliar la figura marina en técnicas mixtas",
    altHominids: "Díptico simétrico de homínidos impresos y capas rosas, rojas y grises de marmoleo",
    altWatercolourMarbling: "Acuarela abstracta de amarillo, azul y rojo atravesada por líneas negras y marmoleo",
    altMarineFigure: "Figura marina sobre textil rojo y turquesa, hecha de bordado, collage, acuarela y fragmentos recombinados",
    researchPart: "Parte I",
    worksTitle: "Investigar",
    worksIntro: "En una investigación terminada solemos ver un resultado coherente. A mí me interesan los borradores: los momentos en que la comprensión vacila y debe retomarse.",
    genesisKicker: "Génesis de una práctica",
    genesisTitle: "Cómo el dibujo entró en la investigación",
    researchTocLabel: "Índice de la investigación",
    researchTocKicker: "En esta parte",
    researchTocGenesis: "La génesis",
    researchTocGenesisText: "Cómo entró el dibujo en la investigación.",
    researchTocMethod: "Las operaciones",
    researchTocMethodText: "Lo que la historieta vuelve posible.",
    researchTocCases: "Los encuentros",
    researchTocCasesText: "Cómo los casos transformaron el método.",
    researchTocProjects: "Los proyectos",
    researchTocProjectsText: "Tres momentos de una investigación en curso.",
    genesisIntro: "No empecé inventando un método. El dibujo se volvió una herramienta de investigación a través de una serie de experiencias.",
    genesis1Title: "Antes del método",
    genesis1Text: "El dibujo ya era una práctica personal y experimental, antes de las ciencias sociales.",
    genesis2Title: "Dibujar el campo",
    genesis2Text: "En la Amazonia colombiana, los dibujos y las acuarelas me enseñaron a ir más despacio y mirar de otra manera.",
    genesis3Title: "Un campo interrumpido",
    genesis3Text: "La pandemia interrumpió el campo. Las imágenes me permitieron volver hacia una experiencia que aún no tenía forma.",
    genesis4Title: "Volver mediante la historieta",
    genesis4Text: "En el IHEAL, los talleres de Romain Dutter condujeron a diecinueve páginas sobre mi llegada a la Amazonia.",
    genesis5Title: "Diana devuelve la mirada",
    genesis5Text: "Al retomar la escena con Diana Gil Bora, la pregunta se invirtió: ¿qué ven los demás del investigador?",
    researchProjectsKicker: "Proyectos de investigación",
    researchProjectsTitle: "Proyectos e historietas dibujadas",
    researchProjectsText: "Cada proyecto aparece primero como un resumen. Ábrelo para recorrer sus imágenes, sus versiones y sus decisiones metodológicas.",
    expandOpen: "Abrir esta sección",
    expandClose: "Cerrar esta sección",
    journeyLabel: "TRAYECTO",
    troubleMeta: "Proyecto doctoral · EHESS · 2026",
    troubleTitle: "Trouble dans l’enquête",
    troubleSubtitle: "Seguir lo que ocurre con una escena cuando es narrada, dibujada, devuelta y retomada.",
    troubleText: "Este proyecto doctoral prolonga los aprendizajes de la memoria. Las escenas problemáticas funcionan como puertas de entrada empíricas: la historieta permite seguir sus interpretaciones sucesivas, ponerlas en circulación y observar qué transforman las devoluciones.",
    troubleNoteLabel: "Pregunta actual",
    troubleQuestion: "¿Qué ocurre con una interpretación cuando puede ser dibujada, discutida, corregida, rechazada o dejada abierta?",
    troubleImage1Caption: "El campo narrado por el investigador",
    troubleImage2Caption: "El campo devuelve la mirada al investigador",
    openTrouble1: "Ampliar la primera página de Trouble dans l’enquête",
    openTrouble2: "Ampliar la segunda página de Trouble dans l’enquête",
    altTrouble1: "Primera página de historieta del proyecto doctoral Trouble dans l’enquête",
    altTrouble2: "Segunda página con interpretaciones divergentes de una situación de campo",
    imposteurMeta: "L’Imposteur · revista doctoral · 2025",
    imposteurTitle: "Entrar al doctorado en otra lengua",
    imposteurText: "Dos páginas autobiográficas vuelven sobre mi llegada a Francia y el doble trabajo impuesto por la lengua académica: pensar en español, reformular en francés y después enfrentar la ortografía como criterio de legitimidad. La historieta aparece a la vez como lenguaje científico y como una forma de abrir un método propio.",
    imposteurNoteLabel: "Miedo al entrar al doctorado",
    imposteurNote: "El aislamiento, la precariedad material y la pérdida de los vínculos sociales.",
    imposteurCaption1: "Llegada a Francia y lengua académica",
    imposteurCaption2: "La historieta como apertura metodológica",
    imposteurCaption3: "El mayor miedo al comenzar el doctorado",
    openImposteur1: "Ampliar la primera página publicada en L’Imposteur",
    openImposteur2: "Ampliar la segunda página publicada en L’Imposteur",
    openImposteur3: "Ampliar la ilustración sobre el miedo al entrar al doctorado",
    altImposteur1: "Página autobiográfica sobre la llegada a Toulouse y las dificultades con la lengua académica francesa",
    altImposteur2: "Página autobiográfica sobre el descubrimiento de la historieta como lenguaje científico",
    altImposteur3: "Personaje aislado en un círculo de luz, rodeado de siluetas y pilas de libros",
    observerMeta: "Memoria de Máster 2 · IHEAL · 2024",
    observerTitle: "Observer et être observé",
    observerText: "Una socioantropología de los antropólogos mediante la historieta. La investigación examina cómo las experiencias de campo, las posiciones sociales y las relaciones con los interlocutores transforman la práctica científica, y cómo el investigador también es observado e interpretado.",
    masterResult: "Memoria: 17/20",
    masterMention: "Mención Très Bien",
    observerCaption1: "La relación de investigación como construcción recíproca",
    observerCaption2: "La historieta como método de investigación",
    observerCaption3: "De la entrevista a la página: el caso de Stéphanie",
    openObserver1: "Ampliar Observer et être observé",
    openObserver2: "Ampliar los dibujos del método de investigación",
    openObserver3: "Ampliar el proceso de Stéphanie",
    altObserver1: "Dos personas sentadas ante una mesa, cada una proyectando una representación distinta del trabajo de campo",
    altObserver2: "Conjunto de dibujos que muestra las etapas para producir una historieta a partir de entrevistas",
    altObserver3: "Retrato, elementos de entrevista y storyboard sobre la experiencia de Stéphanie",
    palimpsesteMeta: "Historieta de campo · 2022–en curso",
    palimpsesteTitle: "Trajet du corps palimpseste",
    palimpsesteSubtitle: "Un trayecto entre Kennedy, Francia y la Amazonia, reescrito desde la relación de investigación.",
    palimpsesteText: "A partir de mi trabajo de campo y de los intercambios con Diana Gil Bora, la historieta reconstruye las condiciones que me llevaron hasta la Amazonia colombiana. No cuenta solamente un desplazamiento geográfico: sigue los recuerdos, las asignaciones y los malentendidos que se depositan en el cuerpo del investigador y transforman su manera de ver.",
    palimpsesteAxisLabel: "Trayecto visible",
    palimpsesteAxis: "Kennedy → Francia → Amazonia → retorno sobre la investigación",
    v3GalleryLabel: "Cinco páginas de la versión 3",
    v3Kicker: "Versión 3 · reescritura actual",
    v3Title: "La escena antes de su explicación",
    v3Intro: "El fuego, la maloca, el mambe y los silencios introducen primero la situación. El recorrido autobiográfico llega después: la interpretación nace en las imágenes antes de ser formulada.",
    v3Caption1: "Entrar en la escena",
    v3Caption2: "Una certeza comienza a vacilar",
    v3Caption3: "El malentendido toma cuerpo",
    v3Caption4: "El cuerpo en la escala del territorio",
    v3Caption5: "Volver a Kennedy, origen de la huella",
    openV3P1: "Ampliar la primera página de la versión 3",
    openV3P2: "Ampliar la segunda página de la versión 3",
    openV3P3: "Ampliar la tercera página de la versión 3",
    openV3P4: "Ampliar la cuarta página de la versión 3",
    openV3P5: "Ampliar la quinta página de la versión 3",
    altV3P1: "Secuencia nocturna con el fuego, la maloca, el investigador y una cucharada de mambe",
    altV3P2: "Conversación en la maloca sobre la Iglesia, los pobres y el pecado ecológico",
    altV3P3: "Diálogo en el que el investigador se sorprende de que un sacerdote tome mambe",
    altV3P4: "El investigador sentado bajo un árbol inmenso junto al agua en la Amazonia",
    altV3P5: "Mapas de Colombia, Bogotá y Kennedy que conducen a un recuerdo de infancia en Casablanca",
    layersKicker: "Palimpsesto de fabricación",
    layersTitle: "Lo que desplaza la reescritura",
    layersIntro: "La primera versión de 2022 no se expone como una segunda obra completa. Cuatro confrontaciones precisas muestran cómo cambiaron el punto de vista, el cuerpo y la escala del relato. Abre cada estrato para ver los dos estados.",
    layer1Title: "De la mirada elevada a la presencia",
    layer1Text: "En 2022, la escena se observaba desde arriba. En la versión 3, mi rostro y mi llegada se intercalan entre la maloca y el mambe: el investigador ya no queda fuera de campo.",
    layer2Title: "Del diálogo al problema relacional",
    layer2Text: "Las palabras siguen siendo cercanas, pero las miradas, las distancias y el tiempo concedido a los gestos hacen visibles la sorpresa del investigador y la respuesta de su interlocutor.",
    layer3Title: "Del símbolo al cuerpo situado",
    layer3Text: "La llama abstracta de la primera versión se convierte en un cuerpo minúsculo bajo un árbol inmenso. El trayecto ya no solo se cuenta: adquiere escala, peso y lugar.",
    layer4Title: "Del recuerdo a la escala del territorio",
    layer4Text: "El recuerdo doméstico se abre ahora mediante encajamientos: Colombia, Bogotá, Kennedy, Casablanca y, finalmente, el apartamento. Volver al origen implica atravesar varias capas de espacio y memoria.",
    layerV1Caption: "V1 · primera formulación · 2022",
    layerV3Caption: "V3 · reescritura actual · 2026",
    openV1P1: "Ampliar la primera página de 2022",
    openV1P3: "Ampliar la tercera página de 2022",
    openV1P4: "Ampliar la cuarta página de 2022",
    openV1P5: "Ampliar la quinta página de 2022",
    altV1P1: "Primera versión de 2022 que observa la maloca desde arriba",
    altV1P3: "Primera versión del diálogo sobre el mambe, el sacerdocio y la Iglesia",
    altV1P4: "Primera versión que asocia el trayecto Francia-Amazonia con una gran llama",
    altV1P5: "Primera versión que abre el recuerdo de infancia en Casablanca con una vista de Bogotá",
    mamaMeta: "Historieta familiar · 2022",
    mamaTitle: "¿Dónde está tu mamá?",
    mamaText: "Un relato personal por la línea materna, atravesado por la memoria, la ausencia y los silencios transmitidos entre generaciones. La imagen hace volver aquello que no fue contado y compone con los vacíos de la historia familiar.",
    storiesMeta: "Historietas · 2023–2024",
    storiesTitle: "Retorno, memoria, filiación",
    storiesText: "Dos relatos regresan hacia la Amazonia colombiana. Retour vers l’Amazonie retoma un antiguo trabajo de campo a partir de un nuevo intercambio con Diana Gil Bora. Où est ta maman explora la memoria familiar, la ausencia materna y los silencios heredados.",
    amazonCaption: "Retour vers l’Amazonie · 2024",
    mamaCaption: "¿Dónde está tu mamá? · 2023",
    storyLabel: "RELATO",
    reportageLabel: "REPORTAJE",
    openAmazon1: "Ampliar Retour vers l’Amazonie",
    openAmazon2: "Ampliar una página de Retour vers l’Amazonie",
    openMama1: "Ampliar Où est ta maman",
    openMama2: "Ampliar la segunda página de Où est ta maman",
    altAmazon1: "Secuencia nocturna en blanco y negro que muestra la llegada a una maloca amazónica",
    altAmazon2: "Página de historieta en blanco y negro alrededor de la coca, el tabaco y la palabra",
    altMama1: "Página en blanco y negro sobre la ausencia de la madre, los recuerdos y la filiación",
    altMama2: "Página dibujada que muestra la trayectoria familiar y rural de la madre",
    galereMeta: "Colectivo de investigación-creación · 2025–2026",
    galereText: "Colectivo cofundado alrededor de la historieta y las ciencias sociales. Talleres, fanzines y carteles transforman las dificultades compartidas de la investigación en materia de creación, mediación y discusión colectiva.",
    galereCaption1: "Una investigación colectiva sobre la investigación",
    galereCaption2: "Cartel para los talleres del colectivo",
    galereCaption3: "La historieta como objeto editorial",
    openGalere1: "Ampliar una historieta de La Galère",
    openGalere2: "Ampliar el cartel de La Galère",
    openGalere3: "Ampliar las ediciones de La Galère",
    altGalere1: "Historieta azul y negra sobre las dificultades compartidas del trabajo de investigación",
    altGalere2: "Acuarela circular multicolor con los miembros del colectivo alrededor de un centro rojo y azul",
    altGalere3: "Fanzines, carteles y páginas impresas producidos por el colectivo La Galère",
    plasticMeta: "Cuaderno · bordado · acuarela · collage · 2019–2025",
    plasticTitle: "Cuerpos, máscaras, transformaciones",
    plasticText: "Una investigación plástica autónoma atravesada por rostros, formas orgánicas, aperturas y figuras dobles. La acuarela se mezcla con hilo, tinta y collage; cada reelaboración conserva la huella de los estados anteriores de la imagen.",
    plasticCaption: "Búsquedas plásticas · técnicas mixtas",
    openPlastic: "Ampliar las búsquedas plásticas",
    altPlastic: "Doble página de búsquedas plásticas con hilos bordados rosados y azules, collages y capas de acuarela muy coloridas",
    createPart: "Parte II",
    creationsTitle: "Crear",
    creationsIntro: "Acuarelas, dibujos, bordados, collages y cuadernos componen una práctica artística personal anterior a mi trabajo en ciencias sociales. Tiene su propia historia y no necesita convertirse en método para existir, aunque algunos gestos circulen entre ambos espacios.",
    workshopPart: "Parte III",
    workshopTitle: "Hacer taller",
    workshopIntro: "Un taller no es solamente un lugar donde transmitir una técnica. Es una situación en la que varias personas dibujan, interpretan y transforman juntas aquello que puede saberse, narrarse o compartirse.",
    workshopProcessKicker: "Una práctica de relación",
    workshopProcessTitle: "El taller fabrica un espacio común.",
    workshopProcessIntro: "No llego con una imagen ya decidida. El marco se construye a partir de lo que cada persona aporta, de las formas que ensaya y de los desacuerdos que aparecen.",
    workshopStep1Title: "Poner en situación",
    workshopStep1Text: "Partir de un relato, una dificultad o una experiencia que pueda compartirse.",
    workshopStep2Title: "Fabricar juntos",
    workshopStep2Text: "Dibujar, recortar, montar y comparar sin imponer una única manera de hacer.",
    workshopStep3Title: "Hacer circular",
    workshopStep3Text: "Transformar los ensayos en fanzine, cartel, exposición u objeto de discusión.",
    constellationKicker: "Acuarelas · collage · papel",
    constellationTitle: "Vía Láctea / Bóvedas celestes",
    constellationText: "Tres paisajes interiores donde la luz se deposita por capas. Vía Láctea reúne pigmentos, fragmentos pegados y raspado sobre formato A4; las dos Bóvedas celestes prolongan ese movimiento en formatos más pequeños, entre cielo, profundidad y fuego.",
    constellationGalleryLabel: "Las dos Bóvedas celestes",
    viaLacteaCaption: "Vía Láctea · acuarela, collage y raspado sobre papel · A4",
    bovedasICaption: "Bóvedas celestes I · acuarela sobre papel · formato pequeño",
    bovedasIICaption: "Bóvedas celestes II · acuarela sobre papel · formato pequeño",
    openViaLactea: "Ampliar Vía Láctea",
    openBovedasI: "Ampliar Bóvedas celestes I",
    openBovedasII: "Ampliar Bóvedas celestes II",
    altViaLactea: "Acuarela turquesa constelada de puntos de color, fragmentos pegados y trazos de raspado",
    altBovedasI: "Acuarela de bóveda celeste con arcos amarillos, naranjas, verdes, rosados y azules",
    altBovedasII: "Acuarela de bóveda celeste roja, negra, azul y turquesa alrededor de un centro luminoso",
    studioKicker: "Taller · obras en proceso · París",
    studioTitle: "El taller como palimpsesto vivo",
    studioText: "Las obras no permanecen aisladas dentro de una carpeta. Se responden en las paredes, las cuerdas y la mesa: acuarelas, papeles recortados, hilos, tintas y ensayos todavía abiertos. Cada desplazamiento produce una relación nueva entre las formas.",
    studioCaption: "Colgar, desplazar, recubrir, retomar: el espacio de trabajo conserva la memoria de los gestos.",
    studioGalleryLabel: "Obras y espacio de trabajo",
    studioMark1: "Vista general · taller",
    studioMark2: "Suspender · hacer dialogar",
    studioMark3: "Muro · estados provisionales",
    studioMark4: "Materia · agua · hilo",
    studioMark5: "Mesa · colores en movimiento",
    openStudio1: "Ampliar la vista del taller",
    openStudio2: "Ampliar las obras suspendidas",
    openStudio3: "Ampliar el muro de búsquedas plásticas",
    openStudio4: "Ampliar las búsquedas de materia",
    openStudio5: "Ampliar la mesa de trabajo",
    altStudio1: "Vista general del taller de Peter Castro con obras, libros y herramientas",
    altStudio2: "Obras orgánicas suspendidas delante de una biblioteca",
    altStudio3: "Muro cubierto de acuarelas, papeles recortados y formas orgánicas",
    altStudio4: "Acuarela azul, materia textil y papel suspendidos en el taller",
    altStudio5: "Mesa de trabajo con acuarelas, pinceles y pequeñas pinturas",
    salesKicker: "Obras originales · ediciones · encargos",
    salesTitle: "Obras originales y encargos.",
    salesText: "Escríbeme con el título de una obra y te responderé con sus dimensiones, técnica, disponibilidad, precio y modalidades de envío. También puedo estudiar un encargo.",
    salesCta: "Consultar disponibilidad y precio ↗",
    reportMeta: "Encargo de reportaje dibujado · ENS · 2026",
    reportTitle: "Observación y evocación",
    reportText: "Dibujos realizados en vivo alrededor de una obra de teatro en la École normale supérieure. El trazo registra momentos observados y evoca presencias ausentes, entre escucha, memoria y traducción visual.",
    reportCaption: "Reportaje dibujado: observación y evocación",
    openReport1: "Ampliar el dibujo de la entrada",
    openReport2: "Ampliar el dibujo del público",
    openReport3: "Ampliar el dibujo del escenario",
    openReport4: "Ampliar el dibujo frente al mar",
    altReport1: "Dibujo en tinta de un grupo reunido a la entrada de un teatro",
    altReport2: "Dibujo del público observando una representación teatral",
    altReport3: "Dibujo de un escenario iluminado con intérpretes alineados",
    altReport4: "Personaje diminuto de pie frente a un mar inmenso dibujado en tinta",
    methodTitle: "Lo que la historieta le hace a la investigación",
    methodIntro: "De este trayecto surgen cuatro operaciones. No forman una receta: describen lo que el dibujo fue haciendo posible, poco a poco, dentro de mis investigaciones.",
    conceptLabel: "Principio de trabajo",
    conceptTitle: "Dibujar no viene después de investigar.",
    conceptText: "El dibujo desplaza la atención, obliga a hacer visibles las decisiones interpretativas y abre la posibilidad de una devolución. Una imagen puede discutirse, corregirse, rechazarse o dejarse abierta.",
    methodProtocolTitle: "Cuatro operaciones aprendidas en la práctica",
    m1Title: "Mirar de otra manera",
    m1Text: "Dibujar durante o después de un encuentro ralentiza la observación y desplaza la atención hacia gestos, distancias y detalles que la toma de notas puede dejar a un lado.",
    m2Title: "Componer, es decir, interpretar",
    m2Text: "Elegir una escena, un encuadre, una secuencia o un silencio obliga a concretar lo que creemos haber comprendido. El montaje expone así las decisiones del investigador.",
    m3Title: "Devolver la imagen",
    m3Text: "Hacer circular la página entre las personas encontradas convierte la interpretación en un objeto discutible. Pueden precisarla, desplazarla, rechazarla o proponer otra escena.",
    m4Title: "Conservar las versiones",
    m4Text: "Una corrección no sustituye silenciosamente el estado anterior. Las versiones conservan el trayecto del análisis y muestran cómo se transformó una comprensión.",
    casesKicker: "El método a través de los casos",
    casesTitle: "Los encuentros hicieron evolucionar el método.",
    casesIntro: "Cada experiencia planteó un problema diferente. Juntas muestran un método que se construye sobre la marcha, no un protocolo aplicado de antemano.",
    caseCeline: "Una escena de llegada solitaria parecía gráficamente coherente, pero era falsa. Su corrección hizo visible mi interpretación y reactivó la investigación.",
    caseStephanie: "El paso de la entrevista al dibujo permitió comprender con mayor precisión las posiciones, emociones y relaciones contenidas en su relato.",
    caseLouise: "La imagen mostró que la migración estructuraba su experiencia más que el trabajo de campo formal que yo creía que debía representar.",
    caseJeanne: "Un libro bordado y un libro mudo plantearon la cuestión de la restitución: ¿qué se puede transmitir sin cerrar el sentido en lugar de la otra persona?",
    caseAdrien: "La distancia entre la imagen producida y su respuesta no fue un fracaso que hubiera que borrar. Condujo a una nueva indagación y a una interpretación revisada.",
    lineagesTitle: "Una genealogía gráfica concentrada",
    lineagesIntro: "Cuatro encuentros intelectuales y prácticos transformaron directamente mi manera de hacer historietas dentro de la investigación.",
    lineage1Text: "Sus talleres en el IHEAL me enseñaron a transformar una experiencia de campo en escenas, secuencias y páginas, sin reducir la historieta a una ilustración.",
    lineage2Text: "Sus experiencias muestran que la imagen puede participar en la producción colectiva del saber y en su circulación, en vez de aparecer solamente al final de la investigación.",
    lineage3Text: "Su trabajo ayuda a pensar lo que el cambio de medio transforma en la postura del investigador, la escritura y las relaciones de la investigación.",
    lineage4Text: "Propone considerar la historieta como una práctica de investigación en sí misma: una manera de pensar mediante el espacio, la secuencia y el montaje.",
    aboutTitle: "Acerca de",
    aboutLead: "Soy antropólogo, artista e investigador colombiano, radicado en París.",
    aboutText: "Formado en Colombia, México y Francia, trabajo en el cruce de la investigación cualitativa, la narración gráfica y la producción de saberes sensibles. Mi trayectoria atraviesa la antropología, las ciencias sociales y la investigación-creación.",
    aboutCollective: "En 2025 cofundé La Galère, un colectivo interuniversitario que desarrolla talleres, fanzines, exposiciones y restituciones dibujadas en ciencias sociales.",
    cvDownload: "Descargar el CV · PDF ↗",
    edu1: "Año preparatorio al doctorado · EHESS",
    edu2: "DIU ArTeC · Investigación-creación · Universidad París 8",
    edu3: "Máster 2 Ciencias Sociales, Antropología · IHEAL, Sorbonne Nouvelle",
    contactKicker: "Investigación · talleres · edición · exposición",
    contactTitle: "Hablemos de un proyecto.",
    footerRole: "Dibujo, investigación e investigación-creación",
    backTop: "Volver al índice ↑"
  },
  en: {
    title: "Peter Castro",
    description: "Portfolio of Peter Castro, anthropologist, artist and researcher: social research, comics and visual creation through layers.",
    skip: "Skip to content",
    navLabel: "Primary navigation",
    homeLabel: "Peter Castro — home",
    languageLabel: "Language",
    lightboxLabel: "Artwork preview",
    close: "Close",
    navResearch: "Inquire",
    navCreations: "Create",
    navWorkshop: "Make together",
    navAbout: "About",
    role: "Anthropologist · artist · researcher",
    heroLine1: "Drawing",
    heroLine2: "worlds,",
    heroLine3: "following their traces,",
    heroLine4: "layer by layer.",
    heroIntro: "I am an anthropologist, artist and researcher. My work unfolds across social-science inquiry, an autonomous personal art practice and the collective creation of workshops.",
    factsLabel: "Key information",
    based: "Paris",
    territories: "Colombia · Mexico · France",
    yearFocus: "Research-creation · 2026",
    pathsLabel: "Three ways into the portfolio",
    partOneLabel: "PART I",
    partTwoLabel: "PART II",
    partThreeLabel: "PART III",
    sitePlanKicker: "Introduction · how to navigate",
    sitePlanTitle: "One site, three practices.",
    sitePlanText: "This portfolio distinguishes three ways of working. Inquire brings together social science and drawn method. Create presents an autonomous personal art practice. Make together gathers experiences produced with other people. The three spaces speak to one another without becoming the same thing.",
    sitePlanLabel: "Portfolio contents",
    pathResearch: "Inquire",
    pathResearchText: "Understand situations through anthropology, fieldwork and drawing.",
    pathCreations: "Create",
    pathCreationsText: "Explore personal forms, materials and worlds.",
    pathWorkshop: "Make together",
    pathWorkshopText: "Produce images and knowledge in relation with other people.",
    palimpsestKicker: "Guiding thread",
    traceLabel: "TRACE 01—∞",
    palimpsestStatement: "See the layers, then return to the origin of the trace.",
    palimpsestBody: "Inquiry, personal creation and workshops remain distinct practices. They meet in a shared attention to layers, transformations and the origins of traces, without becoming a single practice.",
    palimpsestWords: "body · memory · reworking · return",
    heroCaption: "Drawing worlds · after a drawing by Critón",
    heroYear: "2026",
    openHero: "Enlarge Drawing worlds",
    altHero: "Child drawing a world full of figures and forms, reinterpreted by Peter Castro after a drawing by Critón",
    materialKicker: "Gestures, surfaces, reworkings",
    materialTitle: "Intervening in matter",
    materialText: "These works emerge through successive interventions: front and back, marbling layers, watercolour, thread, collage, tearing and recomposition. Each surface keeps the times and materials that transformed it visible.",
    materialGalleryLabel: "Three works through material interventions",
    hominidsCaption: "Front / back · intervention and marbling",
    watercolourMarblingCaption: "Watercolour and marbling",
    marineFigureCaption: "Marine figure · embroidery, collage, watercolour, tearing and recomposition",
    openHominids: "Enlarge the hominid diptych",
    openWatercolourMarbling: "Enlarge watercolour and marbling",
    openMarineFigure: "Enlarge the mixed-media marine figure",
    altHominids: "Symmetrical diptych of printed hominids with pink, red and grey marbling layers",
    altWatercolourMarbling: "Abstract yellow, blue and red watercolour crossed by black lines and marbling",
    altMarineFigure: "Marine figure on red and turquoise textile made with embroidery, collage, watercolour and recomposed fragments",
    researchPart: "Part I",
    worksTitle: "Inquire",
    worksIntro: "Finished research usually shows us a coherent result. I am interested in the drafts: moments when understanding falters and must be taken up again.",
    genesisKicker: "The genesis of a practice",
    genesisTitle: "How drawing entered the inquiry",
    researchTocLabel: "Research contents",
    researchTocKicker: "In this part",
    researchTocGenesis: "The genesis",
    researchTocGenesisText: "How drawing entered the inquiry.",
    researchTocMethod: "The operations",
    researchTocMethodText: "What comics make possible.",
    researchTocCases: "The encounters",
    researchTocCasesText: "How cases transformed the method.",
    researchTocProjects: "The projects",
    researchTocProjectsText: "Three stages of an ongoing inquiry.",
    genesisIntro: "I did not begin by inventing a method. Drawing became an inquiry tool through a series of experiences.",
    genesis1Title: "Before the method",
    genesis1Text: "Drawing was already a personal and experimental practice, before the social sciences.",
    genesis2Title: "Drawing the field",
    genesis2Text: "In the Colombian Amazon, sketches and watercolours taught me to slow down and look differently.",
    genesis3Title: "Interrupted fieldwork",
    genesis3Text: "The pandemic interrupted the fieldwork. Images let me return to an experience that still had no form.",
    genesis4Title: "Returning through comics",
    genesis4Text: "At IHEAL, Romain Dutter’s workshops led to nineteen pages about my arrival in the Amazon.",
    genesis5Title: "Diana returns the gaze",
    genesis5Text: "Revisiting the scene with Diana Gil Bora inverted the question: what do others see in the researcher?",
    researchProjectsKicker: "Research projects",
    researchProjectsTitle: "Projects and drawn narratives",
    researchProjectsText: "Each project first appears as a summary. Open it to explore its images, versions and methodological choices.",
    expandOpen: "Open this section",
    expandClose: "Close this section",
    journeyLabel: "JOURNEY",
    troubleMeta: "Doctoral project · EHESS · 2026",
    troubleTitle: "Trouble dans l’enquête",
    troubleSubtitle: "Following what becomes of a scene as it is narrated, drawn, returned and reworked.",
    troubleText: "This doctoral project extends what I learned through the master’s dissertation. Scenes of trouble become empirical entry points: comics make it possible to follow successive interpretations, circulate them and observe what participants’ responses transform.",
    troubleNoteLabel: "Current question",
    troubleQuestion: "What becomes of an interpretation when it can be drawn, discussed, corrected, refused or left open?",
    troubleImage1Caption: "Fieldwork narrated by the researcher",
    troubleImage2Caption: "Fieldwork returning the gaze",
    openTrouble1: "Enlarge the first page of Trouble dans l’enquête",
    openTrouble2: "Enlarge the second page of Trouble dans l’enquête",
    altTrouble1: "First comics page from the doctoral project Trouble dans l’enquête",
    altTrouble2: "Second page showing competing interpretations of a fieldwork situation",
    imposteurMeta: "L’Imposteur · doctoral journal · 2025",
    imposteurTitle: "Beginning a PhD in another language",
    imposteurText: "Two autobiographical pages revisit my arrival in France and the double labour imposed by academic language: thinking in Spanish, reformulating in French, then facing spelling as a criterion of legitimacy. Comics appear both as a scientific language and as a way of opening up a method of my own.",
    imposteurNoteLabel: "Fear on entering doctoral study",
    imposteurNote: "Isolation, material insecurity and the loss of social ties.",
    imposteurCaption1: "Arriving in France and academic language",
    imposteurCaption2: "Comics as a methodological opening",
    imposteurCaption3: "The greatest fear on entering doctoral study",
    openImposteur1: "Enlarge the first page published in L’Imposteur",
    openImposteur2: "Enlarge the second page published in L’Imposteur",
    openImposteur3: "Enlarge the illustration about fear on entering doctoral study",
    altImposteur1: "Autobiographical page about arriving in Toulouse and struggling with French academic language",
    altImposteur2: "Autobiographical page about discovering comics as a language of research",
    altImposteur3: "An isolated figure in a circle of light, surrounded by silhouettes and piles of books",
    observerMeta: "Master’s dissertation · IHEAL · 2024",
    observerTitle: "Observer et être observé",
    observerText: "A socio-anthropology of anthropologists through comics. The research examines how fieldwork experiences, social positions and relationships with interlocutors transform scientific practice — and how the researcher is also observed and interpreted.",
    masterResult: "Dissertation: 17/20",
    masterMention: "Highest honours",
    observerCaption1: "The research relationship as a reciprocal construction",
    observerCaption2: "Comics as a research method",
    observerCaption3: "From interview to comics page: Stéphanie’s case",
    openObserver1: "Enlarge Observer et être observé",
    openObserver2: "Enlarge the research-method drawings",
    openObserver3: "Enlarge Stéphanie’s process",
    altObserver1: "Two people seated at a table, each projecting a different representation of fieldwork",
    altObserver2: "Assembly of drawings showing how interviews become comics pages",
    altObserver3: "Portrait, interview elements and storyboard around Stéphanie’s experience",
    palimpsesteMeta: "Fieldwork comic · 2022–ongoing",
    palimpsesteTitle: "Trajet du corps palimpseste",
    palimpsesteSubtitle: "A trajectory between Kennedy, France and the Amazon, rewritten through the research relationship.",
    palimpsesteText: "Drawing on my fieldwork and exchanges with Diana Gil Bora, the comic reconstructs the conditions that led me to the Colombian Amazon. It recounts more than a geographical displacement: it follows the memories, social assignments and misunderstandings deposited in the researcher’s body and transforming how he sees.",
    palimpsesteAxisLabel: "Visible trajectory",
    palimpsesteAxis: "Kennedy → France → Amazon → return to the inquiry",
    v3GalleryLabel: "Five pages from version 3",
    v3Kicker: "Version 3 · current rewriting",
    v3Title: "The scene before its explanation",
    v3Intro: "Fire, the maloca, mambe and silence introduce the situation first. The autobiographical path follows: interpretation takes shape in images before it is formulated.",
    v3Caption1: "Entering the scene",
    v3Caption2: "A certainty begins to falter",
    v3Caption3: "The misunderstanding takes bodily form",
    v3Caption4: "The body at the scale of territory",
    v3Caption5: "Returning to Kennedy, origin of the trace",
    openV3P1: "Enlarge the first page of version 3",
    openV3P2: "Enlarge the second page of version 3",
    openV3P3: "Enlarge the third page of version 3",
    openV3P4: "Enlarge the fourth page of version 3",
    openV3P5: "Enlarge the fifth page of version 3",
    altV3P1: "Night sequence showing the fire, the maloca, the researcher and a spoonful of mambe",
    altV3P2: "Conversation in the maloca about the Church, the poor and ecological sin",
    altV3P3: "Dialogue in which the researcher is surprised that a priest takes mambe",
    altV3P4: "The researcher seated beneath an immense tree by the water in the Amazon",
    altV3P5: "Maps of Colombia, Bogotá and Kennedy leading to a childhood memory in Casablanca",
    layersKicker: "Palimpsest of making",
    layersTitle: "What the rewriting shifts",
    layersIntro: "The first version from 2022 is not displayed as a second complete work. Four precise confrontations show instead how viewpoint, body and narrative scale have changed. Open each layer to see both states.",
    layer1Title: "From overview to presence",
    layer1Text: "In 2022, the scene was observed from above. In version 3, my face and arrival are inserted between the maloca and the mambe: the researcher is no longer outside the frame.",
    layer2Title: "From dialogue to relational trouble",
    layer2Text: "The words remain similar, but the gazes, distances and time given to gestures now make the researcher’s surprise and his interlocutor’s response visible.",
    layer3Title: "From symbol to situated body",
    layer3Text: "The first version’s abstract flame becomes a tiny body beneath an immense tree. The trajectory is no longer merely narrated: it acquires scale, weight and place.",
    layer4Title: "From memory to the scale of territory",
    layer4Text: "The domestic memory now opens through nested scales: Colombia, Bogotá, Kennedy, Casablanca and finally the apartment. Returning to the origin means crossing several layers of space and memory.",
    layerV1Caption: "V1 · first formulation · 2022",
    layerV3Caption: "V3 · current rewriting · 2026",
    openV1P1: "Enlarge the first page from 2022",
    openV1P3: "Enlarge the third page from 2022",
    openV1P4: "Enlarge the fourth page from 2022",
    openV1P5: "Enlarge the fifth page from 2022",
    altV1P1: "First 2022 version observing the maloca from above",
    altV1P3: "First version of the dialogue about mambe, priesthood and the Church",
    altV1P4: "First version associating the France-Amazon trajectory with a large flame",
    altV1P5: "First version opening the childhood memory in Casablanca with a view of Bogotá",
    mamaMeta: "Family comic · 2022",
    mamaTitle: "Where is your mother?",
    mamaText: "A personal narrative on the maternal side, shaped by memory, absence and silences passed between generations. Images bring back what was never told and compose with the gaps left in family history.",
    storiesMeta: "Comics · 2023–2024",
    storiesTitle: "Return, memory, kinship",
    storiesText: "Two narratives return to the Colombian Amazon. Retour vers l’Amazonie revisits earlier fieldwork through a new exchange with Diana Gil Bora. Où est ta maman explores family memory, maternal absence and inherited silences.",
    amazonCaption: "Retour vers l’Amazonie · 2024",
    mamaCaption: "Where is your mother? · 2023",
    storyLabel: "NARRATIVE",
    reportageLabel: "REPORTAGE",
    openAmazon1: "Enlarge Retour vers l’Amazonie",
    openAmazon2: "Enlarge a page from Retour vers l’Amazonie",
    openMama1: "Enlarge Où est ta maman",
    openMama2: "Enlarge the second page of Où est ta maman",
    altAmazon1: "Black-and-white night sequence showing an arrival at an Amazonian maloca",
    altAmazon2: "Black-and-white comics page about coca, tobacco and speech",
    altMama1: "Black-and-white page about maternal absence, memory and kinship",
    altMama2: "Drawn page showing the mother’s rural and family trajectory",
    galereMeta: "Research-creation collective · 2025–2026",
    galereText: "A collective co-founded around comics and the social sciences. Workshops, fanzines and posters turn shared research difficulties into material for creation, mediation and collective discussion.",
    galereCaption1: "Collective research about research",
    galereCaption2: "Poster for the collective’s workshops",
    galereCaption3: "Comics as an editorial object",
    openGalere1: "Enlarge a La Galère comic",
    openGalere2: "Enlarge the La Galère poster",
    openGalere3: "Enlarge La Galère publications",
    altGalere1: "Blue-and-black comic about shared difficulties in research work",
    altGalere2: "Multicoloured circular watercolour showing collective members around a red-and-blue centre",
    altGalere3: "Fanzines, posters and printed pages produced by the La Galère collective",
    plasticMeta: "Notebook · embroidery · watercolour · collage · 2019–2025",
    plasticTitle: "Bodies, masks, transformations",
    plasticText: "An autonomous visual practice shaped by faces, organic forms, openings and double figures. Watercolour mixes with thread, ink and collage; each reworking retains traces of the image’s earlier states.",
    plasticCaption: "Visual experiments · mixed media",
    openPlastic: "Enlarge the visual experiments",
    altPlastic: "Double-page visual experiment with pink and blue embroidery, collage and vivid layers of watercolour",
    createPart: "Part II",
    creationsTitle: "Create",
    creationsIntro: "Watercolours, drawings, embroidery, collage and notebooks form a personal art practice that predates my work in the social sciences. It has its own history and does not need to become a method in order to exist, even if some gestures circulate between the two spaces.",
    workshopPart: "Part III",
    workshopTitle: "Make together",
    workshopIntro: "A workshop is not only a place where a technique is transmitted. It is a situation in which people draw, interpret and transform together what can be known, narrated or shared.",
    workshopProcessKicker: "A relational practice",
    workshopProcessTitle: "The workshop makes a common space.",
    workshopProcessIntro: "I do not arrive with an image already decided. The frame is built from what people bring, the forms they try and the disagreements that emerge.",
    workshopStep1Title: "Set the situation",
    workshopStep1Text: "Begin with a narrative, a difficulty or an experience that can be shared.",
    workshopStep2Title: "Make together",
    workshopStep2Text: "Draw, cut, assemble and compare without imposing a single way of making.",
    workshopStep3Title: "Put into circulation",
    workshopStep3Text: "Turn experiments into a fanzine, poster, exhibition or object for discussion.",
    constellationKicker: "Watercolours · collage · paper",
    constellationTitle: "Vía Láctea / Bóvedas celestes",
    constellationText: "Three inner landscapes where light settles in layers. Vía Láctea brings together pigments, pasted fragments and scraping on A4 paper; the two Bóvedas celestes continue this movement in smaller formats, between sky, depth and fire.",
    constellationGalleryLabel: "The two Bóvedas celestes",
    viaLacteaCaption: "Vía Láctea · watercolour, collage and scraping on paper · A4",
    bovedasICaption: "Bóvedas celestes I · watercolour on paper · small format",
    bovedasIICaption: "Bóvedas celestes II · watercolour on paper · small format",
    openViaLactea: "Enlarge Vía Láctea",
    openBovedasI: "Enlarge Bóvedas celestes I",
    openBovedasII: "Enlarge Bóvedas celestes II",
    altViaLactea: "Turquoise watercolour with constellations of coloured dots, pasted fragments and scraped marks",
    altBovedasI: "Celestial-vault watercolour with yellow, orange, green, pink and blue arches",
    altBovedasII: "Red, black, blue and turquoise celestial-vault watercolour around a luminous centre",
    studioKicker: "Studio · works in progress · Paris",
    studioTitle: "The studio as a living palimpsest",
    studioText: "The works do not remain isolated in a folder. They answer one another across walls, cords and the worktable: watercolours, cut paper, thread, ink and experiments still left open. Each displacement creates a new relationship between forms.",
    studioCaption: "Hanging, shifting, covering, returning: the workspace retains the memory of its gestures.",
    studioGalleryLabel: "Works and studio space",
    studioMark1: "Wide view · studio",
    studioMark2: "Suspend · bring into dialogue",
    studioMark3: "Wall · provisional states",
    studioMark4: "Matter · water · thread",
    studioMark5: "Table · colours in motion",
    openStudio1: "Enlarge the studio view",
    openStudio2: "Enlarge the suspended works",
    openStudio3: "Enlarge the wall of visual experiments",
    openStudio4: "Enlarge the material experiments",
    openStudio5: "Enlarge the worktable",
    altStudio1: "Wide view of Peter Castro’s studio with works, books and tools",
    altStudio2: "Organic works suspended in front of a bookcase",
    altStudio3: "Wall covered with watercolours, cut paper and organic forms",
    altStudio4: "Blue watercolour, textile matter and paper suspended in the studio",
    altStudio5: "Worktable with watercolours, brushes and small paintings",
    salesKicker: "Original works · editions · commissions",
    salesTitle: "Original works and commissions.",
    salesText: "Write to me with the title of a work and I will reply with its dimensions, technique, availability, price and shipping options. I can also discuss a commission.",
    salesCta: "Ask about availability and price ↗",
    reportMeta: "Commissioned drawn reportage · ENS · 2026",
    reportTitle: "Observation and evocation",
    reportText: "Drawings made on the spot around a theatre performance at the École normale supérieure. The line records observed moments and evokes absent presences — between listening, memory and visual translation.",
    reportCaption: "Drawn reportage: observation and evocation",
    openReport1: "Enlarge the entrance sketch",
    openReport2: "Enlarge the audience sketch",
    openReport3: "Enlarge the stage sketch",
    openReport4: "Enlarge the drawing facing the sea",
    altReport1: "Ink sketch of a gathering at a theatre entrance",
    altReport2: "Sketch of an audience watching a theatre performance",
    altReport3: "Sketch of an illuminated stage with performers standing in a line",
    altReport4: "Tiny figure standing before a vast sea drawn in ink",
    methodTitle: "What comics do to inquiry",
    methodIntro: "Four operations emerge from this trajectory. They are not a recipe: they describe what drawing gradually made possible within my inquiries.",
    conceptLabel: "Working principle",
    conceptTitle: "Drawing does not come after inquiry.",
    conceptText: "Drawing shifts attention, forces interpretive choices into view and opens the possibility of return. An image can be discussed, corrected, refused or left open.",
    methodProtocolTitle: "Four operations learned through practice",
    m1Title: "Look differently",
    m1Text: "Drawing during or after an encounter slows observation and shifts attention towards gestures, distances and details that note-taking alone can leave aside.",
    m2Title: "Compose, therefore interpret",
    m2Text: "Choosing a scene, frame, sequence or silence forces us to make concrete what we think we understood. Montage exposes the researcher’s decisions.",
    m3Title: "Return the image",
    m3Text: "Circulating the page among the people encountered turns interpretation into something discussable. They can specify it, shift it, refuse it or propose another scene.",
    m4Title: "Keep the versions",
    m4Text: "A correction does not silently replace the previous state. Versions preserve the trajectory of analysis and show how an understanding was transformed.",
    casesKicker: "Method through cases",
    casesTitle: "Encounters made the method evolve.",
    casesIntro: "Each experience posed a different problem. Together they show a method being built in practice rather than a protocol applied in advance.",
    caseCeline: "A scene of solitary arrival looked graphically coherent, but it was false. Her correction made my interpretation visible and reopened the inquiry.",
    caseStephanie: "Moving from interview to drawing made it possible to understand more precisely the positions, emotions and relationships contained in her narrative.",
    caseLouise: "The image revealed that migration structured her experience more deeply than the formal fieldwork I thought I should represent.",
    caseJeanne: "An embroidered book and a silent book raised the question of return: what can be shared without closing meaning on someone else’s behalf?",
    caseAdrien: "The gap between the image produced and his response was not a failure to erase. It led to further inquiry and a revised interpretation.",
    lineagesTitle: "A focused graphic genealogy",
    lineagesIntro: "Four intellectual and practical encounters directly changed how I make comics within research.",
    lineage1Text: "His workshops at IHEAL taught me how to turn a fieldwork experience into scenes, sequences and pages without reducing comics to illustration.",
    lineage2Text: "Their experiments show that images can take part in the collective production and circulation of knowledge instead of arriving only at the end of research.",
    lineage3Text: "His work helps me think through what a change of medium transforms in the researcher’s position, writing and fieldwork relationships.",
    lineage4Text: "She proposes comics as a research practice in its own right: a way of thinking through space, sequence and montage.",
    aboutTitle: "About",
    aboutLead: "I am a Colombian anthropologist, artist and researcher based in Paris.",
    aboutText: "Educated in Colombia, Mexico and France, I work at the intersection of qualitative research, graphic narrative and the production of sensory forms of knowledge. My path moves through anthropology, the social sciences and research-creation.",
    aboutCollective: "In 2025 I co-founded La Galère, an inter-university collective developing workshops, fanzines, exhibitions and drawn forms of research return in the social sciences.",
    cvDownload: "Download CV · PDF ↗",
    edu1: "Preparatory year for doctoral study · EHESS",
    edu2: "DIU ArTeC · Research-creation · Paris 8 University",
    edu3: "Master’s in Social Sciences, Anthropology · IHEAL, Sorbonne Nouvelle",
    contactKicker: "Research · workshops · publishing · exhibitions",
    contactTitle: "Let’s discuss a project.",
    footerRole: "Drawing, fieldwork & research-creation",
    backTop: "Back to contents ↑"
  }
};

const languageButtons = [...document.querySelectorAll("[data-lang]")];
const textNodes = [...document.querySelectorAll("[data-i18n]")];
const ariaNodes = [...document.querySelectorAll("[data-i18n-aria]")];
const imageNodes = [...document.querySelectorAll("[data-alt]")];
let currentLanguage = "fr";

function saveLanguage(language) {
  try {
    localStorage.setItem("portfolio-language", language);
  } catch {
    // The language still changes when storage is unavailable.
  }
}

function loadLanguage() {
  try {
    return localStorage.getItem("portfolio-language");
  } catch {
    return null;
  }
}

function setLanguage(language, persist = true) {
  const dictionary = translations[language] || translations.fr;
  currentLanguage = translations[language] ? language : "fr";
  document.documentElement.lang = currentLanguage;
  document.title = dictionary.title;
  document.querySelector('meta[name="description"]').setAttribute("content", dictionary.description);

  textNodes.forEach((node) => {
    const value = dictionary[node.dataset.i18n];
    if (value) node.textContent = value;
  });

  ariaNodes.forEach((node) => {
    const value = dictionary[node.dataset.i18nAria];
    if (value) node.setAttribute("aria-label", value);
  });

  imageNodes.forEach((image) => {
    const value = dictionary[image.dataset.alt];
    if (value) image.alt = value;
  });

  languageButtons.forEach((button) => {
    button.setAttribute("aria-pressed", String(button.dataset.lang === currentLanguage));
  });

  document.querySelectorAll(".expand-toggle").forEach(updateExpandableButton);

  if (persist) saveLanguage(currentLanguage);
}

languageButtons.forEach((button) => {
  button.addEventListener("click", () => setLanguage(button.dataset.lang));
});

const savedLanguage = loadLanguage();
const browserLanguage = navigator.language.slice(0, 2);
setLanguage(savedLanguage || (translations[browserLanguage] ? browserLanguage : "fr"), false);

document.getElementById("year").textContent = String(new Date().getFullYear());

const reduceMotion = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
const revealNodes = [...document.querySelectorAll(".reveal")];

if (reduceMotion || !("IntersectionObserver" in window)) {
  revealNodes.forEach((node) => node.classList.add("is-visible"));
} else {
  const revealObserver = new IntersectionObserver(
    (entries, observer) => {
      entries.forEach((entry) => {
        if (entry.isIntersecting) {
          entry.target.classList.add("is-visible");
          observer.unobserve(entry.target);
        }
      });
    },
    { threshold: 0.08, rootMargin: "0px 0px -5%" }
  );
  revealNodes.forEach((node) => revealObserver.observe(node));
}

const mainContent = document.getElementById("main");
const readingOrder = [
  ".hero",
  ".site-plan",
  ".palimpsest-bridge",
  "#recherche",
  ".research-toc",
  "#research-genesis",
  "#methode",
  "#research-projects",
  'article[aria-labelledby="project-observer"]',
  'article[aria-labelledby="project-palimpseste"]',
  'article[aria-labelledby="project-trouble"]',
  ".creations-intro",
  ".constellation-scene",
  ".project-color",
  ".material-process",
  'article[aria-labelledby="project-mama"]',
  'article[aria-labelledby="project-reportage"]',
  ".studio-scene",
  ".sales-band",
  '[data-space="workshop"].work-intro',
  ".workshop-process",
  'article[aria-labelledby="project-galere"]',
  ".about",
  'article[aria-labelledby="project-imposteur"]',
  ".about-contact"
]
  .map((selector) => document.querySelector(selector))
  .filter((node) => node && node.parentElement === mainContent);

readingOrder.forEach((node) => mainContent.appendChild(node));

const routeLinks = [...document.querySelectorAll("[data-route]")];
const spaceNodes = [...document.querySelectorAll("[data-space]")];
const routeAliases = {
  home: "home",
  top: "home",
  research: "research",
  recherche: "research",
  "research-genesis": "research",
  methode: "research",
  "research-cases": "research",
  "research-projects": "research",
  create: "create",
  creations: "create",
  workshop: "workshop",
  about: "about",
  apropos: "about"
};

function currentSpaceFromHash() {
  const key = window.location.hash.replace("#", "");
  return routeAliases[key] || "home";
}

function showSpace({ scroll = false } = {}) {
  const space = currentSpaceFromHash();
  document.body.dataset.currentSpace = space;

  spaceNodes.forEach((node) => {
    node.hidden = node.dataset.space !== space;
  });

  routeLinks.forEach((link) => {
    const active = link.dataset.route === space;
    link.classList.toggle("is-active", active);
    if (active) link.setAttribute("aria-current", "page");
    else link.removeAttribute("aria-current");
  });

  if (scroll) {
    const targetId = window.location.hash.replace("#", "");
    const target = targetId ? document.getElementById(targetId) : null;
    const targetSpace = target?.dataset.space || target?.closest("[data-space]")?.dataset.space;
    if (target && targetSpace === space) {
      target.scrollIntoView({ behavior: reduceMotion ? "auto" : "smooth", block: "start" });
    } else {
      window.scrollTo({ top: 0, behavior: reduceMotion ? "auto" : "smooth" });
    }
  }
}

routeLinks.forEach((link) => {
  link.addEventListener("click", () => {
    if (link.dataset.route === currentSpaceFromHash()) showSpace({ scroll: true });
  });
});

window.addEventListener("hashchange", () => {
  if (window.location.hash === "#main") return;
  showSpace({ scroll: true });
});

showSpace({ scroll: Boolean(window.location.hash) });

const expandableNodes = [...document.querySelectorAll(".route-expandable")];

function updateExpandableButton(button) {
  const expandable = button.closest(".route-expandable");
  const isOpen = expandable?.classList.contains("is-open") || false;
  const dictionary = translations[currentLanguage];
  const label = button.querySelector("span");
  const symbol = button.querySelector("i");

  if (label) label.textContent = dictionary[isOpen ? "expandClose" : "expandOpen"];
  if (symbol) symbol.textContent = isOpen ? "−" : "+";
  button.setAttribute("aria-expanded", String(isOpen));
}

expandableNodes.forEach((expandable, index) => {
  const heading = [...expandable.children].find(
    (child) => child.classList.contains("project-info") || child.classList.contains("section-heading")
  );

  if (!heading) return;

  const button = document.createElement("button");
  button.type = "button";
  button.className = "expand-toggle";
  button.setAttribute("aria-expanded", "false");
  button.innerHTML = '<span></span><i aria-hidden="true">+</i>';
  heading.insertAdjacentElement("afterend", button);

  const details = [...expandable.children].filter(
    (child) => child !== heading && child !== button
  );
  details.forEach((child) => child.setAttribute("data-expandable-content", `expandable-content-${index + 1}`));

  button.addEventListener("click", () => {
    expandable.classList.toggle("is-open");
    updateExpandableButton(button);
  });

  updateExpandableButton(button);
});

const lightbox = document.getElementById("lightbox");
const lightboxImage = document.getElementById("lightbox-image");
const lightboxCaption = document.getElementById("lightbox-caption");
const closeButton = lightbox.querySelector(".lightbox-close");

document.querySelectorAll("[data-lightbox]").forEach((button) => {
  button.addEventListener("click", () => {
    const dictionary = translations[currentLanguage];
    const previewImage = button.querySelector("img");
    lightboxImage.src = button.dataset.lightbox;
    lightboxImage.alt = previewImage?.alt || "";
    lightboxCaption.textContent = dictionary[button.dataset.captionKey] || "";
    lightbox.showModal();
  });
});

closeButton.addEventListener("click", () => lightbox.close());
lightbox.addEventListener("click", (event) => {
  if (event.target === lightbox) lightbox.close();
});
lightbox.addEventListener("close", () => {
  lightboxImage.removeAttribute("src");
  lightboxImage.alt = "";
  lightboxCaption.textContent = "";
});
